FROM python:3.8-slim-buster

WORKDIR /app1

#COPY backend/requirements.txt .
COPY requirements.txt .

RUN pip install -r requirements.txt

#COPY backend .
COPY . .

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]