FROM python:3.8-slim-buster

WORKDIR /app1

#COPY requirements.txt .
COPY backend/requirements.txt .

RUN pip install -r requirements.txt

#COPY . .
COPY backend .

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]